Old Studying Notebook

In [ ]:
# pip install numpy 

In [2]:
import numpy

In [1]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr) 

[1 2 3 4 5]


In [4]:
import numpy as np 

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

arr = np.array((10, 20, 30, 40, 50))

print(arr)

print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array(42)

print(arr)

42


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5]) 

print(arr)

[1 2 3 4 5]


In [10]:
print(arr[3])

4


In [11]:
print(arr[-2])

4


In [12]:
print(3 in arr) 

True


In [13]:
print(arr.shape)

(5,)


In [14]:
print(arr.ndim) 

1


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:
print(arr[0,0])

1


In [5]:
print(arr[1,2])

6


In [18]:
print(arr[1,:])

[4 5 6]


In [19]:
print(arr[0,:2]) 

[1 2]


In [20]:
print(arr[-1,1])

5


In [21]:
print(arr[-1,-2:])

[5 6]


In [22]:
print(arr.shape)

(2, 3)


In [23]:
print(arr.ndim)

2


In [24]:
print(6 in arr)

True


In [25]:
print(0 in arr)

False


In [26]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [11, 22, 33]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 22 33]]]


In [27]:
arr.shape

(2, 2, 3)

In [28]:
print(arr[0, 1, 2])

6


In [29]:
print(arr[1, 0, -1])

9


In [ ]:
import numpy as np

a = np.array(42)

b = np.array([1, 2, 3, 4, 5])

c = np.array([[1, 2, 3], [4, 5, 6]])

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)       

int32


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4],float)

print(arr.dtype)

float64


In [33]:
print(arr)

[1. 2. 3. 4.]


In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])


x = arr.copy()      # [1, 2, 3, 4, 5]

arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [35]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.view()   # x = arr 

x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [36]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)

print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [37]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

newarr = arr.reshape(3, 2, 4)

print(newarr)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [6]:
# Error

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3])


for x in arr:
  print(x)

1
2
3


In [41]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = arr1 + arr2 

print(arr)

[5 7 9]


In [44]:
x = np.ones((4))

print(x)

[1. 1. 1. 1.]


In [45]:
x = np.ones((4,5))

print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [46]:
x = np.ones((4,5,3))

print(x)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [47]:
x = np.zeros((4))

print(x)

[0. 0. 0. 0.]


In [ ]:
x = np.zeros((4,5,3)) #arr num - rows -cols

print(x)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)    

(array([3, 5, 6], dtype=int64),)


In [50]:
import numpy as np

arr = np.array([14, 2, 0, 45, 5, 61, 4, 80])

x = np.where(arr%2 == 0)

print(x)

(array([0, 1, 2, 6, 7], dtype=int64),)


In [51]:
import numpy as np

arr = np.array([10, 2, 30, 4, 5, 16, 7, 48])

x = np.where(arr%2 == 1)

print(x)

(array([4, 6], dtype=int64),)


In [8]:
arr = np.arange(10)

print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [53]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

print(arr[0] - arr[2])

7
-2


In [54]:
arr1 = np.array([ 10 , 20 , 5])
arr2 = np.array([ 4 , 6 , 2 ])

print(arr1 - arr2)
print(arr1 + arr2)
print(arr1 * arr2)

[ 6 14  3]
[14 26  7]
[ 40 120  10]


In [55]:
print(arr1 % arr2)

[2 2 1]


In [56]:
print(arr1**arr2)

[   10000 64000000       25]


In [57]:
import numpy as np

arr = np.array([4, 9, 49, 81])

print(np.sqrt(arr))

[2. 3. 7. 9.]


In [58]:
import numpy as np

arr = np.array([4.3, 9.8, 49.2, 81.7])

print(np.floor(arr))

[ 4.  9. 49. 81.]


In [59]:
print(np.ceil(arr))

[ 5. 10. 50. 82.]


In [60]:
print(np.rint(arr))

[ 4. 10. 49. 82.]


In [61]:
p = np.pi

print(p)

3.141592653589793


In [62]:
arr = np.array([1,28,12,39])

print(arr.mean())

print(arr.max())

print(arr.min())

20.0
39
1


In [63]:
arr = np.array([1,4,6,0,3,9,6])

print(arr.argmin())

print(arr.argmax())

3
5


In [64]:
arr = np.array([1,4,6,0,3,9,6])

print(arr >= 6)

[False False  True False False  True  True]


In [53]:
from numpy import random

x = random.randint(100)

print(x)

4


In [51]:
from numpy import random

x = random.rand()

print(x)

0.6321726671366773


# Pandas


In [67]:
# pip install pandes 

In [7]:
import pandas 

In [8]:
import pandas as pd

df = pd.read_csv("data.csv")

print(df) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [9]:
print(pd.DataFrame(df))

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [10]:
pd.DataFrame(df)

,Duration,Pulse,Maxpulse,Calories
0,60,110,130,409.1
1,60,117,145,479.0
2,60,103,135,340.0
3,45,109,175,282.4
4,45,117,148,406.0
...,...,...,...,...
164,60,105,140,290.8
165,60,110,145,300.0
166,60,115,145,310.2
167,75,120,150,320.4


In [72]:
print(df.to_string()) 

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [1]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

print(mydataset)

{'cars': ['BMW', 'Volvo', 'Ford'], 'passings': [3, 7, 2]}


In [73]:
import pandas as pd

mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'passings': [3, 7, 2]
}

myvar = pd.DataFrame(mydataset)

print(myvar)

    cars  passings
0    BMW         3
1  Volvo         7
2   Ford         2


In [74]:
myvar

,cars,passings
0,BMW,3
1,Volvo,7
2,Ford,2


In [3]:
a = [1, 7, 2]

print(a)

[1, 7, 2]


In [2]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a)

print(myvar)

0    1
1    7
2    2
dtype: int64


In [76]:
print(myvar[0])

1


In [77]:
import pandas as pd

a = [1, 7, 2]

myvar = pd.Series(a, index = ['x', 'y', 'z'])

print(myvar)

x    1
y    7
z    2
dtype: int64


In [78]:
print(myvar["y"])

7


In [4]:
calories = {"day1": 420, "day2": 380, "day3": 390}

print(calories)

{'day1': 420, 'day2': 380, 'day3': 390}


In [79]:
import pandas as pd

calories = {"day1": 420, "day2": 380, "day3": 390}

myvar = pd.Series(calories)

print(myvar)

day1    420
day2    380
day3    390
dtype: int64


In [5]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

print(data)

{'calories': [420, 380, 390], 'duration': [50, 40, 45]}


In [80]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

myvar = pd.DataFrame(data)

print(myvar)

   calories  duration
0       420        50
1       380        40
2       390        45


In [81]:
myvar

,calories,duration
0,420,50
1,380,40
2,390,45


In [15]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)
print('__________________________')
print(df.loc[0])

   calories  duration
0       420        50
1       380        40
2       390        45
__________________________
calories    420
duration     50
Name: 0, dtype: int64


In [83]:
#use a list of indexes:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40


In [84]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df) 

      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [85]:
#refer to the named index:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64


In [86]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df)

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]


In [87]:
df

,Duration,Pulse,Maxpulse,Calories
0,60,110,130,409.1
1,60,117,145,479.0
2,60,103,135,340.0
3,45,109,175,282.4
4,45,117,148,406.0
...,...,...,...,...
164,60,105,140,290.8
165,60,110,145,300.0
166,60,115,145,310.2
167,75,120,150,320.4


In [88]:
df.max()

Duration     300.0
Pulse        159.0
Maxpulse     184.0
Calories    1860.4
dtype: float64

In [89]:
max_duration = df['Duration'].max()

In [90]:
df[df['Duration'] == max_duration]

,Duration,Pulse,Maxpulse,Calories
69,300,108,143,1500.2


In [91]:
df.min()

Duration     15.0
Pulse        80.0
Maxpulse    100.0
Calories     50.3
dtype: float64

In [92]:
df.sum()

Duration    10790.0
Pulse       18161.0
Maxpulse    22654.0
Calories    61629.6
dtype: float64

In [93]:
import pandas as pd

data = {
  "Duration":{
    "0":60,
    "1":60,
    "2":60,
    "3":45,
    "4":45,
    "5":60
  },
  "Pulse":{
    "0":110,
    "1":117,
    "2":103,
    "3":109,
    "4":117,
    "5":102
  },
  "Maxpulse":{
    "0":130,
    "1":145,
    "2":135,
    "3":175,
    "4":148,
    "5":127
  },
  "Calories":{
    "0":409,
    "1":479,
    "2":340,
    "3":282,
    "4":406,
    "5":300
  }
}

df = pd.DataFrame(data)

print(df) 

   Duration  Pulse  Maxpulse  Calories
0        60    110       130       409
1        60    117       145       479
2        60    103       135       340
3        45    109       175       282
4        45    117       148       406
5        60    102       127       300


In [94]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.head())

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


In [95]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.head(10))

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0
5        60    102       127     300.0
6        60    110       136     374.0
7        45    104       134     253.3
8        30    109       133     195.1
9        60     98       124     269.0


In [96]:
print(df.tail()) 

     Duration  Pulse  Maxpulse  Calories
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4


In [97]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB
None


In [17]:
import pandas as pd

df = pd.read_csv('data.csv')

print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45   

In [ ]:
import pandas as pd

df = pd.read_csv('data.csv')

new_df = df.dropna() # delets rows with nan values

print(new_df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60   

In [99]:
df.describe()

,Duration,Pulse,Maxpulse,Calories
count,169.000000,169.000000,169.000000,164.000000
mean,63.846154,107.461538,134.047337,375.790244
std,42.299949,14.510259,16.450434,266.379919
min,15.000000,80.000000,100.000000,50.300000
25%,45.000000,100.000000,124.000000,250.925000
50%,60.000000,105.000000,131.000000,318.600000
75%,60.000000,111.000000,141.000000,387.600000
max,300.000000,159.000000,184.000000,1860.400000


In [18]:
import pandas as pd

# Read Salaries.csv as a dataframe called sal
sal = pd.read_csv('Salaries.csv')


In [19]:
# Check the head of the DataFrame
sal.head()


,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN


In [20]:
# Use the .info() method to find out how many entries there are
sal.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [21]:
# Use the .describe() method to get some statistics for the data
sal.describe()


,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Status
count,148654.000000,148045.000000,148650.000000,148650.000000,112491.000000,148654.000000,148654.000000,148654.000000,0.0,0.0
mean,74327.500000,66325.448840,5066.059886,3648.767297,25007.893151,74768.321972,93692.554811,2012.522643,NaN,NaN
std,42912.857795,42764.635495,11454.380559,8056.601866,15402.215858,50517.005274,62793.533483,1.117538,NaN,NaN
min,1.000000,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000,NaN,NaN
25%,37164.250000,33588.200000,0.000000,0.000000,11535.395000,36168.995000,44065.650000,2012.000000,NaN,NaN
50%,74327.500000,65007.450000,0.000000,811.270000,28628.620000,71426.610000,92404.090000,2013.000000,NaN,NaN
75%,111490.750000,94691.050000,4658.175000,4236.065000,35566.855000,105839.135000,132876.450000,2014.000000,NaN,NaN
max,148654.000000,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000,NaN,NaN


In [22]:
# What is the average BasePay?
sal['BasePay'].mean()


66325.4488404877

In [23]:
# What is the highest amount of OvertimePay in the dataset?
sal['OvertimePay'].max()


245131.88

In [28]:
sal[sal['OvertimePay'] == sal['OvertimePay'].max()]['EmployeeName'] 

1    GARY JIMENEZ
Name: EmployeeName, dtype: object

In [26]:
# What is the job title of JOSEPH DRISCOLL?
sal[sal['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle'] 


24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [107]:
# How much does JOSEPH DRISCOLL make (including benefits)?
sal[sal['EmployeeName']=='JOSEPH DRISCOLL']['TotalPayBenefits']


24    270324.91
Name: TotalPayBenefits, dtype: float64

In [108]:

# What is the name of highest paid person (including benefits)?
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].max()]['EmployeeName']


0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [109]:

# What is the name of lowest paid person (including benefits)?
sal[sal['TotalPayBenefits'] == sal['TotalPayBenefits'].min()]['EmployeeName']


148653    Joe Lopez
Name: EmployeeName, dtype: object