1. Create a 3x3 array that contains a diagonal of nines

In [ ]:
import numpy as np

arr = np.arange(9).reshape(3,3)
di = np.diag_indices(3)
arr[di] = 9
print(arr)


[[9 1 2]
 [3 9 5]
 [6 7 9]]


2. Create a 7x7 matrix of all ones Inside it place a 5x5 "hole" of zeros (from the 2nd to the 6th row/column)

Finally place the number 5 exactly in the center of the matrix



In [8]:
arr1 = np.ones((7,7))

hole = np.zeros((5,5))
hole[2,2] = 5

arr1[1:-1 , 1:-1] = hole

print(arr1)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 5. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


3. Ask the user for a number n. Then, use broadcasting to create a n x n np array that has its first column full of ones, its second column full of twos, its third column full of threes, etc…

In [11]:
n=int(input())

nxn = np.zeros((n,n))
cols=0
for x in range(n):
    nxn[:,cols] = x+1
    cols +=1


print(nxn)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


4. Generate a random 5x5 matrix with integer values between 0 and 100

1- Find the maximum value in each row 

2- Find the sum of each column 

3- Calculate the overall Mean (average) of the matrix

4- Use Boolean Masking to create a new matrix where all values > 50 become 1, and all values <= 50 become 0

In [ ]:

rnd = np.random.randint(0,100, size= (5,5))
print(rnd)

'''
cols=0
for x in range(5):
    print(f"max of col{cols} : {max(rnd[:,cols])}")
    cols+=1'''

'''
for col in range(5):
    print(f"sum of col{col} : {sum(rnd[:,col])}")
    cols+=1    '''

print(f"Max of each col :{rnd.max(axis=0)}")  # if for rows axis = 1
print(f"Sum of each col :{rnd.sum(axis=0)}")
print(f"Avarge of each col :{rnd.mean()}")

# creating  boolean mask for the required coditions
mask1 = rnd >50
mask2 = rnd<=50

# we change elements in the array
rnd[mask1]=1
rnd[mask2]=0
print(rnd)


[[54  0 47 38 91]
 [ 1 73 84 54 71]
 [76 37 52 75 76]
 [43 43 99 53 91]
 [56 62 45 52 68]]
Max of each col :[76 73 99 75 91]
Sum of each col :[230 215 327 272 397]
Avarge of each col :57.64
[[1 0 0 0 1]
 [0 1 1 1 1]
 [1 0 1 1 1]
 [0 0 1 1 1]
 [1 1 0 1 1]]


5. Create the following array: arr = np.arange(1, 31).reshape(6, 5)

Extract the following sub-sections using only Slicing or List Indexing:

1- The small 2x2 square containing [[11, 12], [16, 17]]

2- The elements [2, 8, 14, 20]

3- All rows with even indices (Row 0, Row 2, Row 4)

In [34]:
arr = np.arange(1, 31).reshape(6, 5)
print(arr)

squ_2x2 =arr[2:4,0:2]
print(squ_2x2)

#diag() & diagonal() both returns an array object not a list
offset_diag =np.diag(arr,k=1)
diag_offset= arr.diagonal(offset=1)
print(offset_diag)
print(type(diag_offset))

for row in range(6):
    if  row %2 == 0:
        print(arr[row,:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
[ 2  8 14 20]
<class 'numpy.ndarray'>
[1 2 3 4 5]
[11 12 13 14 15]
[21 22 23 24 25]


6. You have a 1D array representing student scores: scores = np.array([45, 88, 92, 30, 50, 76, 99, 12, 65])

1- Use Boolean Indexing to filter and print only the passing grades (>= 50)

2- check if any student got a perfect score of 100

3- check if all students passed



In [ ]:
scores = np.array([45, 88, 92, 30, 50, 76, 99, 12, 65])

'''mask = scores>=50        #boolean masking
filtered = scores[mask]
print(f'Passing : {filtered}')'''

filtered=[]               #boolean index filtering
for score in scores:
    if score>=50:
        filtered.append(True)
    else:
        filtered.append(False)

print(f" passing : {scores[filtered]}")



'''if 100  in scores:
   print("Perfect score achieved")
else:
    print('Perfect score not achieved')'''

if scores.any() == 100:
    print("Perfect score achieved")
else :
    print("Perfect score not achieved")



if scores.all() >= 50:
    print("all pased")
else :
    print("There is faliers")




 passing : [88 92 50 76 99 65]
Perfect score not achieved
There is faliers
