In [ ]:
#numpy - numeric python 
# ndarray = n -dimensional array

import numpy 
np = numpy.array([0,1,2,3,4,5])

# range from 0 to 9
np1 =numpy.arange(10)  
print(np1)

# step array by 2
np3 = numpy.arange(0,10 ,2)  # from 0 to 10 step 2
print (np3)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [ ]:
# Zeros
np4 = numpy.zeros(6)
print(np4)

# Multidimensional
np5 = numpy.zeros((3,4))
print(np5)

# Full
np6 = numpy.full((10),8) #A size 10 arr of 8s
print(np6)

# Full - Multidimensional
np7 = numpy.full((3,4),8) #A size 3*4 arr of 8s
print(np7)

# Flatten : just set the resape to -1 هيفردها
np8 = np7.reshape(-1)
print(np8)


[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[8 8 8 8 8 8 8 8 8 8]
[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]
[8 8 8 8 8 8 8 8 8 8 8 8]


In [ ]:
# Slicing Numpy Array
# arrays can be accessed by +ve index or -ve index as well

import numpy as np
arr1 = np.array([1,2,3,4,5,6,7,8,9])
print(arr1[1:5])

# from an index to the end (+ve)
print(arr1[3:])
# (-ve)
print(arr1[-3:-1])

# slicing + Step
print(arr1[0:5 :2])

#step on entire array
print(arr1[::3])



[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[1 3 5]
[1 4 7]


In [ ]:
# Diagonal Methods
# Example 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Method 1: Using numpy.diagonal()
diag1 = arr.diagonal()  # Returns main diagonal
print("Diagonal using diagonal():", diag1)

# Method 2: Using numpy.diag() on a 2D array
diag2 = np.diag(arr)  # Also returns main diagonal
print("Diagonal using diag():", diag2)

# Method 3: Extracting an offset diagonal
diag_offset = arr.diagonal(offset=1)  # Above main diagonal
print("Diagonal with offset=1:", diag_offset)

# Method 4: Creating a diagonal matrix from a 1D array
vec = np.array([10, 20, 30])# هيحطها ف مصفوفه صفريه ويخلي عناصرها الاساسيه هي القطر
diag_matrix = np.diag(vec)
print("Diagonal matrix from vector:\n", diag_matrix)

Diagonal using diagonal(): [1 5 9]
Diagonal using diag(): [1 5 9]
Diagonal with offset=1: [2 6]
Diagonal matrix from vector:
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


In [ ]:
# search for univerasl functions its simply like math functions
# Copy : making a copy from an array means that it remains the same even if the original changed
# View : view an array if the original is modified ,then the view also will be changed
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()      # [1, 2, 3, 4, 5]

arr[0] = 42

print(arr)
print(x)



'''arr = np.array([1, 2, 3, 4, 5])
x = arr.view()   # x = arr 

x[0] = 31

print(arr)
print(x)'''

[42  2  3  4  5]
[1 2 3 4 5]


'arr = np.array([1, 2, 3, 4, 5])\nx = arr.view()   # x = arr \n\nx[0] = 31\n\nprint(arr)\nprint(x)'

In [ ]:
# iterating over an array without loops
# np.nditer()

mtx3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np.nditer(mtx3):
    print(x)

    # بدل ما اعمل تلت لوبس

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
# Sorting - numerical & alphabetical
# np.sort(array_name)



In [ ]:
#searching in arrays
#np.where(condition) givex index value


# Filtering arrays with boolean index vs boolean masking
# Masking :بحط الشرط ف متغير بعد كدا بستخدمه ف المصفوفه 
# Indexing : هنا بستخدم الشرط مباشر ف المصفوفه



#.all()بتطبق الشرط ع الارراي 
#.any() checks if the condition achieved for any value of the array

# numpy.random.randint(low, high=None, size=None, dtype=int)
#low (int) – Lowest integer (inclusive) if high is specified, otherwise highest integer (exclusive).
#high (int, optional) – One above the largest integer to be drawn. If None, range is [0, low]
#size (int or tuple of ints, optional) – Output shape. If None, returns a single integer.
#dtype (optional) – Desired output data type (default is int).


In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

arr = arr1 + arr2 

print(arr)

[1 2 3 4 5 6]
[5 7 9]
